---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: geerlingguy/docker-centos7-ansible
    pre_build_image: true
  - name: centos8
    image: geerlingguy/docker-centos8-ansible
    pre_build_image: true
  - name: debian9
    image: geerlingguy/docker-debian9-ansible
    pre_build_image: true
  - name: ubuntu2004
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true
  - name: ubuntu1804
    image: geerlingguy/docker-ubuntu1804-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
